@echo off
echo מאתחל את גיט...
git init
echo מוסיף את כל הקבצים...
git add .
echo יוצר שמירה ראשונה...
git commit -m "Initial family tree app"
echo מגדיר את הענף הראשי...
git branch -M main
echo מתחבר ל-Repository שלך...
git remote add origin https://github.com/yetsion77/FAMILY.git
echo מעלה את הקוד לגיטהאב...
git push -u origin main
echo סיימנו! הקוד שוגר לגיטהאב.
pause
